# Generated by Django 2.2.17 on 2021-01-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField()),
                ('student_name', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=64)),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('mark', models.CharField(max_length=16)),
            ],
        ),
    ]
